WORKING_DIR="${HOME}/git/experiments/client_autoscribe"
CELERY_BIN="${WORKING_DIR}/.venv/bin/celery"
CELERY_APP="client_autoscribe_worker_v2"
CELERY_QUEUES="client_autoscribe_v2"
CELERYD_MULTI="multi"
CELERYD_OPTS="-Ofair"
CONCURRENCY="6"
CELERYD_PID_FILE="${HOME}/logs/${CELERY_QUEUES}/%n.pid"
CELERYD_LOG_FILE="${HOME}/logs/${CELERY_QUEUES}/%n%I.log"
CELERYD_LOG_LEVEL="INFO"
